### PR TITLE
Add basic auth for machine accounts

### PR DESCRIPTION
**Pull request by barreiro**
port of Hyperfoil/Horreum#1813 to the go client

### CODE REVIEW

**Review by lampajr — COMMENTED** [review]
Hi @barreiro,
Will check this in while but after a quick check I see you added the basic auth as fallback when the default authentication errors but I am not completely sure that is always right.

I was thinking to make the authentication mechanism configurable, e.g., adding another option in the `configs.go`, e.g., with an enum like `BEARER` or `BASIC`. With this approach we don't make any assumption and let the user choose the right auth based on the account he would like to use. wdyt?

**Comment by barreiro** [comment]
I have tried different approaches for the java client. In the end settled for this approach in order to avoid migration to users.

Adding an option is possible, but it should be make consistent for all client implementations.

**Review by lampajr — CHANGES_REQUESTED** [review]
>I have tried different approaches for the java client. In the end settled for this approach in order to avoid migration to users.
>
>Adding an option is possible, but it should be make consistent for all client implementations.

Yeah that's fair but I am not 100% sure this is going to work as you expected here.

The fallback is used only when the `setupAuthProvider` fails, but this happens if and only if something goes wrong retrieving the `config/keycloak` data or there is no connection established.

I mean I don't think that this is what we actually want, you can check the same in the test you updated.. it uses the fallback because the connection was refused.

**Comment by lampajr** [comment]
>Yeah that's fair but I am not 100% sure this is going to work as you expected here.

For instance if you try to use wrong credentials agains a running system, it will still use the Bearer token approach without falling back to basic one

**Review by lampajr — APPROVED** [review]
LGTM!

Thanks @barreiro :pray:

**Pull request merged**
